Repository NLnetLabs/domain, pull requests merged in 2024-10, with the labels that each got.

#398 Enforce dgram max response size limit.
  src/net/server/dgram.rs
Labels: enhancement

#352 Fix zone walking to include non-leaf CNAMEs
  src/zonetree/in_memory/read.rs
Labels: bug

#386 Link to definition of DNS
  src/lib.rs
Labels: documentation

#401 Zone walking should not exclude glue
  examples/query-zone.rs
  src/net/server/middleware/xfr/axfr.rs
  src/zonetree/in_memory/read.rs
  src/zonetree/update.rs
  src/zonetree/walk.rs
  test-data/server/axfr_out.rpl
Labels: bug

#370 Add and improve middleware related RustDocs.
  src/net/server/middleware/mandatory.rs
  src/net/server/middleware/mod.rs
  src/net/server/middleware/stream.rs
Labels: documentation, needs-review

#403 More EDNS(0) fixes.
  src/net/server/middleware/edns.rs
Labels: bug

#402 Fix indentation and remove unused settings in auth-zones test.
  test-data/server/auth_zones.rpl
Labels: needs-review

#407 Empty NSEC3 salt should be a dash in zone presentation format.
  src/rdata/nsec3.rs
Labels: bug

#412 Fix compilation if only feature net is enabled.
  src/net/xfr/mod.rs
Labels: bug

#396 Introduce `HashCompressor` for name compression
  Cargo.lock
  Cargo.toml
  src/base/message_builder.rs
  src/base/mod.rs
Labels: needs-review

#429 Fix bug where using UnknownRecord data fails when compressed names ar…
  src/net/server/single_service.rs
Labels: bug, needs-review

#417 FIX: NSEC records should include themselves in the generated bitmap.
  src/sign/records.rs
Labels: bug, needs-review
