Repository NLnetLabs/domain, pull requests merged in 2024-11, with the labels that each got.

#406 Loading, storing, and generating DNSSEC keys
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/sign/bytes.rs
  src/sign/common.rs
  src/sign/key.rs
  src/sign/mod.rs
  src/sign/openssl.rs
  src/sign/ring.rs
  src/validate.rs
  test-data/dnssec-keys/Ktest.+005+00439.ds
  test-data/dnssec-keys/Ktest.+005+00439.key
  test-data/dnssec-keys/Ktest.+005+00439.private
  test-data/dnssec-keys/Ktest.+007+22204.ds
  test-data/dnssec-keys/Ktest.+007+22204.key
  test-data/dnssec-keys/Ktest.+007+22204.private
  test-data/dnssec-keys/Ktest.+008+60616.ds
  test-data/dnssec-keys/Ktest.+008+60616.key
  test-data/dnssec-keys/Ktest.+008+60616.private
  test-data/dnssec-keys/Ktest.+013+42253.ds
  test-data/dnssec-keys/Ktest.+013+42253.key
  test-data/dnssec-keys/Ktest.+013+42253.private
  test-data/dnssec-keys/Ktest.+014+33566.ds
  test-data/dnssec-keys/Ktest.+014+33566.key
  test-data/dnssec-keys/Ktest.+014+33566.private
  test-data/dnssec-keys/Ktest.+015+56037.ds
  test-data/dnssec-keys/Ktest.+015+56037.key
  test-data/dnssec-keys/Ktest.+015+56037.private
  test-data/dnssec-keys/Ktest.+016+07379.ds
  test-data/dnssec-keys/Ktest.+016+07379.key
  test-data/dnssec-keys/Ktest.+016+07379.private
Labels: breaking, needs-review, unstable feature

#438 Check example compilation in the CI workflow.
  .github/workflows/ci.yml
Labels: needs-review

#432 Add missing required features to Cargo.toml for examples
  .github/workflows/ci.yml
  Cargo.toml
  examples/client-transports.rs
Labels: bug, needs-review, unstable feature

#439 Don't run CI checks twice per push to PR branches.
  .github/workflows/ci.yml
Labels: enhancement

#460 Apply fixes for new issues found by Clippy 1.83.0
  src/base/charstr.rs
  src/base/dig_printer.rs
  src/base/message.rs
  src/base/name/absolute.rs
  src/base/name/chain.rs
  src/base/name/parsed.rs
  src/base/name/relative.rs
  src/base/name/traits.rs
  src/base/name/uncertain.rs
  src/base/opt/algsig.rs
  src/base/opt/chain.rs
  src/base/opt/cookie.rs
  src/base/opt/expire.rs
  src/base/opt/exterr.rs
  src/base/opt/keepalive.rs
  src/base/opt/keytag.rs
  src/base/opt/nsid.rs
  src/base/opt/padding.rs
  src/base/opt/subnet.rs
  src/base/question.rs
  src/base/rdata.rs
  src/base/record.rs
  src/base/serde.rs
  src/base/wire.rs
  src/net/client/load_balancer.rs
  src/net/client/redundant.rs
  src/net/client/request.rs
  src/net/server/dgram.rs
  src/net/server/middleware/tsig.rs
  src/net/xfr/protocol/iterator.rs
  src/rdata/dnssec.rs
  src/rdata/rfc1035/txt.rs
  src/rdata/svcb/value.rs
  src/resolv/lookup/host.rs
  src/resolv/stub/conf.rs
  src/resolv/stub/mod.rs
  src/stelline/client.rs
  src/utils/base16.rs
  src/utils/base32.rs
  src/utils/base64.rs
  src/validate.rs
  src/validator/group.rs
  src/zonefile/inplace.rs
  src/zonetree/traits.rs
  src/zonetree/types.rs
Labels: needs-review
